# Pandas II
- Filtrado / Ordenamiento / Selección
- Uniendo y concatenando dataframes
- Joins
- Creando Campos
- Guardado de un DataFrame

In [1]:
import pandas as pd
import numpy as np

# import ssl
# ssl._create_default_https_context = ssl._create_unverified_context

In [2]:
df_base = pd.read_csv('https://raw.githubusercontent.com/AngelTintaya/datasets/main/coordenadas.tsv', sep='\t')
df_base.head(5)

    CODIGO FUENTE      PROV         DPTO      DIST          X          Y
0  9700083    API  AREQUIPA     AREQUIPA     VITOR -71.938900 -16.466000
1  9700813    API  AREQUIPA     AREQUIPA  AREQUIPA -71.536221 -16.395467
2  9702087    API  TRUJILLO  LA LIBERTAD  TRUJILLO -79.037315  -8.128069
3  9701858    API  AREQUIPA     AREQUIPA     CAYMA -71.549208 -16.392485
4  9700022    API  AREQUIPA     AREQUIPA  SOCABAYA -71.524635 -16.441262

# Filtrado, Ordenamiento y Selección
- Filtrado: Un filtro
- Filtrado: Múltiples filtros
- Ordenamiento de datos en un Dataframe
- Selección de datos en Dataframe
- Selección loc
- Selección iloc

In [3]:
df_base.head(1)

    CODIGO FUENTE      PROV      DPTO   DIST        X       Y
0  9700083    API  AREQUIPA  AREQUIPA  VITOR -71.9389 -16.466

# Filtrado: Un filtro

In [4]:
# Dataframe cuya fuente proviene de una API
df_base['FUENTE']=='API'

0        True
1        True
2        True
3        True
4        True
         ...
14912    True
14913    True
14914    True
14915    True
14916    True
Name: FUENTE, Length: 14917, dtype: bool

In [5]:
df_base[df_base['FUENTE']=='API'].head(2)

    CODIGO FUENTE      PROV      DPTO      DIST          X          Y
0  9700083    API  AREQUIPA  AREQUIPA     VITOR -71.938900 -16.466000
1  9700813    API  AREQUIPA  AREQUIPA  AREQUIPA -71.536221 -16.395467

# Filtrado: Múltiples Filtros

In [6]:
(df_base['FUENTE']=='API') & ~(df_base['DPTO'].isin(['AREQUIPA', 'LA LIBERTAD']))

0        False
1        False
2        False
3        False
4        False
         ...
14912    False
14913    False
14914    False
14915    False
14916    False
Length: 14917, dtype: bool

In [7]:
# DataFrame que proviene de una API y cuyo departamento no sea de AREQUIPA ni de LA LIBERTAD
df_base[(df_base['FUENTE']=='API') & ~(df_base['DPTO'].isin(['AREQUIPA', 'LA LIBERTAD']))].head(2)

      CODIGO FUENTE       PROV  DPTO     DIST          X          Y
545  9701029    API  SAN ROMAN  PUNO  JULIACA -70.127531 -15.502608
577  9701699    API  SAN ROMAN  PUNO  JULIACA -70.131694 -15.491775

In [8]:
# DataFrame que no venga de una API y cuyo departamento sea nulo
df_base[(df_base['FUENTE'] != 'API') & (df_base['DPTO'].isnull())].head(2)

     CODIGO FUENTE PROV DPTO DIST   X   Y
6   9701816    WBS  NaN  NaN  NaN NaN NaN
11  9700906    WBS  NaN  NaN  NaN NaN NaN

In [9]:
# DataFrame que no venga de una API y cuyo departamento no sea nulo
df_base[(df_base['FUENTE'] != 'API') & (df_base['DPTO'].notnull())].head(2)
# df_base[(df_base['FUENTE'] != 'API') | (df_base['DPTO'].notnull())].head(2)
# df_base[(df_base['FUENTE'] != 'API') & ~(df_base['orig_dpto'].isnull())].head(2)

,CODIGO,FUENTE,PROV,DPTO,DIST,X,Y
285,9700432,WBS,AREQUIPA,AREQUIPA,ALTO SELVA ALEGRE,-71.535029,-16.403066
1548,9700102,WBS,AREQUIPA,AREQUIPA,CERRO COLORADO,NaN,NaN

In [10]:
df_base['FUENTE'].value_counts()

FUENTE
API    13405
WBS     1512
Name: count, dtype: int64

In [11]:
df_base['FUENTE'].unique()

array(['API', 'WBS'], dtype=object)

# Ordenamiento de Datos en un Dataframe

In [12]:
df_base.sort_values(by=['FUENTE','PROV','CODIGO'], ascending=[True,False,True], inplace=True)
df_base.reset_index(inplace=True, drop=True)
df_base.head()

    CODIGO FUENTE      PROV         DPTO      DIST          X         Y
0  9699985    API  TRUJILLO  LA LIBERTAD  TRUJILLO -79.019552 -8.104854
1  9699985    API  TRUJILLO  LA LIBERTAD  TRUJILLO -79.021932 -8.113123
2  9699985    API  TRUJILLO  LA LIBERTAD  TRUJILLO -79.038636 -8.126615
3  9699985    API  TRUJILLO  LA LIBERTAD  TRUJILLO -79.040091 -8.100903
4  9699986    API  TRUJILLO  LA LIBERTAD  TRUJILLO -79.012899 -8.087046

# Selección de Datos en un Dataframe

In [13]:
df_base[['CODIGO', 'FUENTE']][7:10]

    CODIGO FUENTE
7  9699987    API
8  9699987    API
9  9699987    API

# Selección loc

In [14]:
df_base.loc[7:9, ['CODIGO', 'FUENTE']]

    CODIGO FUENTE
7  9699987    API
8  9699987    API
9  9699987    API

In [15]:
df_base.loc[[3, 7, 9], ['CODIGO', 'FUENTE']]

    CODIGO FUENTE
3  9699985    API
7  9699987    API
9  9699987    API

# Selección iloc

In [16]:
df_base.iloc[7:9, :2]

    CODIGO FUENTE
7  9699987    API
8  9699987    API

In [17]:
df_base.iloc[7:9, [0,-2]]

    CODIGO          X
7  9699987 -79.037664
8  9699987 -79.035856

In [18]:
df_base.iloc[[1, 3], [0,-2]]

    CODIGO          X
1  9699985 -79.021932
3  9699985 -79.040091

# Uniendo y Concatenando Dataframes
- pd.concat()
- df.append()

In [19]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']},
                    index=[0, 1, 2])
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [20]:
df2 = pd.DataFrame({'A': ['A3', 'A4', 'A5'],
                    'B': ['B3', 'B4', 'B5'],
                    'C': ['C3', 'C4', 'C5'],
                    'D': ['D3', 'D4', 'D5']},
                     index=[3, 4, 5])
df2

    A   B   C   D
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [21]:
df3 = pd.DataFrame({'B': ['B2', 'B3', 'B7'],
                    'D': ['D2', 'D3', 'D7'],
                    'F': ['F2', 'F3', 'F7']},
                    index=[2, 3, 7])
df3

    B   D   F
2  B2  D2  F2
3  B3  D3  F3
7  B7  D7  F7

# Concatenando DataFrames: pd.concat()

In [22]:
# df.concat()
pd.concat([df1,df2])

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [23]:
pd.concat([df3,df1])

    B   D    F    A    C
2  B2  D2   F2  NaN  NaN
3  B3  D3   F3  NaN  NaN
7  B7  D7   F7  NaN  NaN
0  B0  D0  NaN   A0   C0
1  B1  D1  NaN   A1   C1
2  B2  D2  NaN   A2   C2

In [24]:
# Ordenando columnas
pd.concat([df3,df1], sort=True)

     A   B    C   D    F
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
7  NaN  B7  NaN  D7   F7
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN

In [25]:
pd.concat([df3,df1]).sort_index(axis = 1)

     A   B    C   D    F
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
7  NaN  B7  NaN  D7   F7
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN

In [26]:
# Ordenando indices
pd.concat([df3,df1]).sort_index(axis = 0)

    B   D    F    A    C
0  B0  D0  NaN   A0   C0
1  B1  D1  NaN   A1   C1
2  B2  D2  NaN   A2   C2
2  B2  D2   F2  NaN  NaN
3  B3  D3   F3  NaN  NaN
7  B7  D7   F7  NaN  NaN

In [27]:
# Reseteando Indices
pd.concat([df3,df1], sort=True).reset_index(drop=True)

     A   B    C   D    F
0  NaN  B2  NaN  D2   F2
1  NaN  B3  NaN  D3   F3
2  NaN  B7  NaN  D7   F7
3   A0  B0   C0  D0  NaN
4   A1  B1   C1  D1  NaN
5   A2  B2   C2  D2  NaN

# Joins
- Unión con llave en común
- Merge con llave distinta
- Unión con múltiples llaves
- Left / Rigth / Inner / Outer Join

In [28]:
df_base.FUENTE.value_counts()

FUENTE
API    13405
WBS     1512
Name: count, dtype: int64

In [29]:
df_base.groupby('FUENTE')['CODIGO'].count()

FUENTE
API    13405
WBS     1512
Name: CODIGO, dtype: int64

In [30]:
# Creando DataFrame Descriptivo
df_desfuente = pd.DataFrame({'FUENTE':['API','WBS'],
                             'FNT':['API','WBS'],
                             'DESFUENTE':['API de Google','Webscrapimng a Google Maps'],
                             'ORIGEN':['UM_COORD_EMPRESA','WEB PAGE']
                            })
df_desfuente.head()

  FUENTE  FNT                   DESFUENTE            ORIGEN
0    API  API               API de Google  UM_COORD_EMPRESA
1    WBS  WBS  Webscrapimng a Google Maps          WEB PAGE

In [31]:
# Cruce utilizando un campo en común
df_cruce = pd.merge(df_base,
                    df_desfuente[['FUENTE', 'DESFUENTE']],
                    on = 'FUENTE',
                    how = 'left' # right, inner
                    )
df_cruce.head(2)

,CODIGO,FUENTE,PROV,DPTO,DIST,X,Y,DESFUENTE
0,9699985,API,TRUJILLO,LA LIBERTAD,TRUJILLO,-79.019552,-8.104854,API de Google
1,9699985,API,TRUJILLO,LA LIBERTAD,TRUJILLO,-79.021932,-8.113123,API de Google

In [32]:
# Cruce utilizando diferentes campos
df_cruce = pd.merge(df_base,
                    df_desfuente[['FNT', 'DESFUENTE']],
                    left_on = ['FUENTE'],
                    right_on = ['FNT'],
                    how = 'inner'
                    )
df_cruce.head(2)

,CODIGO,FUENTE,PROV,DPTO,DIST,X,Y,FNT,DESFUENTE
0,9699985,API,TRUJILLO,LA LIBERTAD,TRUJILLO,-79.019552,-8.104854,API,API de Google
1,9699985,API,TRUJILLO,LA LIBERTAD,TRUJILLO,-79.021932,-8.113123,API,API de Google

In [33]:
# BONUS: Borrando una columna en un dataframe: .drop()
df_cruce.drop('FNT', inplace=True, axis=1)
df_cruce.drop(['X', 'Y'], inplace=True, axis=1)
df_cruce.head(2)

    CODIGO FUENTE      PROV         DPTO      DIST      DESFUENTE
0  9699985    API  TRUJILLO  LA LIBERTAD  TRUJILLO  API de Google
1  9699985    API  TRUJILLO  LA LIBERTAD  TRUJILLO  API de Google

In [34]:
# BONUS: Borrando una columna en un dataframe: del
del df_cruce['PROV']
df_cruce.head(2)

    CODIGO FUENTE         DPTO      DIST      DESFUENTE
0  9699985    API  LA LIBERTAD  TRUJILLO  API de Google
1  9699985    API  LA LIBERTAD  TRUJILLO  API de Google

In [35]:
# BONUS: Borrando una columna en un dataframe: .pop()
df_cruce.pop('DPTO')

0        LA LIBERTAD
1        LA LIBERTAD
2        LA LIBERTAD
3        LA LIBERTAD
4        LA LIBERTAD
            ...
14912            NaN
14913            NaN
14914            NaN
14915            NaN
14916            NaN
Name: DPTO, Length: 14917, dtype: object

In [36]:
df_cruce.head(2)

    CODIGO FUENTE      DIST      DESFUENTE
0  9699985    API  TRUJILLO  API de Google
1  9699985    API  TRUJILLO  API de Google

In [37]:
dict_data = {'nombre': ['Luis', 'Pedro', 'Pedro', 'Luis'],
             'edad': [20, 30, 25, 20],
             'Distrito': ['SJL', 'ATE', 'SJM', 'SJL']}

df_data = pd.DataFrame(dict_data)
df_data

  nombre  edad Distrito
0   Luis    20      SJL
1  Pedro    30      ATE
2  Pedro    25      SJM
3   Luis    20      SJL

In [38]:
df_data.drop_duplicates()

  nombre  edad Distrito
0   Luis    20      SJL
1  Pedro    30      ATE
2  Pedro    25      SJM

In [39]:
df_data.drop_duplicates(subset=['nombre'])

  nombre  edad Distrito
0   Luis    20      SJL
1  Pedro    30      ATE

In [40]:
df_data.drop_duplicates(subset=['nombre'], keep='last')

  nombre  edad Distrito
2  Pedro    25      SJM
3   Luis    20      SJL

# Campos Calculados
- Creando un campo
- Rellenando nulos: fillna
- Cambiando tipo de datos
- Lambda Functions
- Trabajando con fechas
- Renombrado columnas
- Mapeando campos: .map()
- Ejercicios

In [41]:
dict_clase = {'codigo':[9876654,7665498,6598764,5498766,8976654],
             'edad':[26,np.nan,30,42,38],
             'ingreso':[2500,2500,3500,4800,4100],
             'estado_civil':['Soltero','Soltero','Casado','Casado','Soltero'],
             'fecmatricula':['25/07/2022','21/07/2022','28/07/2022','26/07/2022','22/07/2022']
            }
df_clase = pd.DataFrame(dict_clase)
df_clase

    codigo  edad  ingreso estado_civil fecmatricula
0  9876654  26.0     2500      Soltero   25/07/2022
1  7665498   NaN     2500      Soltero   21/07/2022
2  6598764  30.0     3500       Casado   28/07/2022
3  5498766  42.0     4800       Casado   26/07/2022
4  8976654  38.0     4100      Soltero   22/07/2022

In [42]:
# Creando un campo
df_clase['anho'] = '2022'
df_clase.head(2)

    codigo  edad  ingreso estado_civil fecmatricula  anho
0  9876654  26.0     2500      Soltero   25/07/2022  2022
1  7665498   NaN     2500      Soltero   21/07/2022  2022

In [43]:
df_clase['ingreso_2'] = df_clase['ingreso']*2
df_clase.head(2)

    codigo  edad  ingreso estado_civil fecmatricula  anho  ingreso_2
0  9876654  26.0     2500      Soltero   25/07/2022  2022       5000
1  7665498   NaN     2500      Soltero   21/07/2022  2022       5000

In [44]:
del df_clase['anho'], df_clase['ingreso_2']
df_clase.head()

    codigo  edad  ingreso estado_civil fecmatricula
0  9876654  26.0     2500      Soltero   25/07/2022
1  7665498   NaN     2500      Soltero   21/07/2022
2  6598764  30.0     3500       Casado   28/07/2022
3  5498766  42.0     4800       Casado   26/07/2022
4  8976654  38.0     4100      Soltero   22/07/2022

# Rellenando Nulos

In [45]:
# Rellenando nulos: fillna
df_clase.edad.mean()

np.float64(34.0)

In [46]:
df_clase['edad'] = df_clase['edad'].fillna(df_clase.edad.mean())
df_clase.head()

    codigo  edad  ingreso estado_civil fecmatricula
0  9876654  26.0     2500      Soltero   25/07/2022
1  7665498  34.0     2500      Soltero   21/07/2022
2  6598764  30.0     3500       Casado   28/07/2022
3  5498766  42.0     4800       Casado   26/07/2022
4  8976654  38.0     4100      Soltero   22/07/2022

In [47]:
'1234'.zfill(5)

'01234'

In [48]:
df_clase['codigo'].dtypes

dtype('int64')

# Cambiando tipo de dato

In [49]:
# Campos Calculados: Cambiando tipo de dato: .astype()
df_clase['DNI'] = df_clase['codigo'].astype('str').str.zfill(8)
df_clase.head(2)

    codigo  edad  ingreso estado_civil fecmatricula       DNI
0  9876654  26.0     2500      Soltero   25/07/2022  09876654
1  7665498  34.0     2500      Soltero   21/07/2022  07665498

In [50]:
df_clase['EC'] = df_clase['estado_civil'].astype('str').str[0].str.upper()
df_clase.head(2)

    codigo  edad  ingreso estado_civil fecmatricula       DNI EC
0  9876654  26.0     2500      Soltero   25/07/2022  09876654  S
1  7665498  34.0     2500      Soltero   21/07/2022  07665498  S

In [51]:
df_clase['next_year'] = df_clase['fecmatricula'].astype('str').str[-4:].astype('int')+1
df_clase.head(2)

    codigo  edad  ingreso estado_civil fecmatricula       DNI EC  next_year
0  9876654  26.0     2500      Soltero   25/07/2022  09876654  S       2023
1  7665498  34.0     2500      Soltero   21/07/2022  07665498  S       2023

In [52]:
df_clase['month'] = df_clase['fecmatricula'].astype('datetime64[ns]').dt.month
df_clase.head(2)

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,EC,next_year,month
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,S,2023,7
1,7665498,34.0,2500,Soltero,21/07/2022,07665498,S,2023,7

In [53]:
df_clase['day'] = df_clase['fecmatricula'].astype('datetime64[ns]').dt.day
df_clase.head(2)

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,EC,next_year,month,day
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,S,2023,7,25
1,7665498,34.0,2500,Soltero,21/07/2022,07665498,S,2023,7,21

In [54]:
df_clase['cod_mes'] = df_clase['fecmatricula'].astype('datetime64[ns]').dt.strftime('%Y%m')
df_clase.head(2)

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,EC,next_year,month,day,cod_mes
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,S,2023,7,25,202207
1,7665498,34.0,2500,Soltero,21/07/2022,07665498,S,2023,7,21,202207

In [55]:
df_clase['formatted_date'] = df_clase['fecmatricula'].astype('datetime64[ns]').dt.strftime('%d de %m del %Y')
df_clase.head(2)

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,EC,next_year,month,day,cod_mes,formatted_date
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,S,2023,7,25,202207,25 de 07 del 2022
1,7665498,34.0,2500,Soltero,21/07/2022,07665498,S,2023,7,21,202207,21 de 07 del 2022

In [56]:
df_clase['cod_date'] = pd.to_datetime(df_clase['formatted_date'], format='%d de %m del %Y').dt.strftime('%Y%m%d')
df_clase.head(2)

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,EC,next_year,month,day,cod_mes,formatted_date,cod_date
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,S,2023,7,25,202207,25 de 07 del 2022,20220725
1,7665498,34.0,2500,Soltero,21/07/2022,07665498,S,2023,7,21,202207,21 de 07 del 2022,20220721

# Lambda Functions en DataFrames

In [57]:
df_clase = df_clase[['codigo','edad','ingreso','estado_civil','fecmatricula', 'DNI']]
df_clase.head(2)

    codigo  edad  ingreso estado_civil fecmatricula       DNI
0  9876654  26.0     2500      Soltero   25/07/2022  09876654
1  7665498  34.0     2500      Soltero   21/07/2022  07665498

In [58]:
# Aplicando Lambda Functions en una columna
# # Cuando se utilizan series no es necesarip asignar un axis
df_clase['TIP_INGRESO'] =  df_clase['ingreso'].apply(lambda x: 'ALTO' if x > 3000 else 'BAJO')
df_clase.head(3)

    codigo  edad  ingreso estado_civil fecmatricula       DNI TIP_INGRESO
0  9876654  26.0     2500      Soltero   25/07/2022  09876654        BAJO
1  7665498  34.0     2500      Soltero   21/07/2022  07665498        BAJO
2  6598764  30.0     3500       Casado   28/07/2022  06598764        ALTO

In [59]:
df_clase['CODMESMATRICULA'] = df_clase['fecmatricula'].apply(lambda x: x.split('/')[2]+x.split('/')[1])
df_clase.head(1)

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,TIP_INGRESO,CODMESMATRICULA
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,BAJO,202207

In [60]:
# Aplicando lambda function a multiples columnas
# Al utilizar Dataframe, es necesario utilizar un axis
df_clase['TIP_INGRESO2'] = df_clase[[
    'ingreso', 'edad'
    ]].apply(lambda x:
             'ALTO' if x['ingreso'] > 4000 else 'MEDIO' if x['ingreso'] > 2000 and x['edad'] < 30 else 'BAJO',
             axis = 1)  # (Manda la columna) Aplica funcion a cada fila
df_clase.head(2)

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,TIP_INGRESO,CODMESMATRICULA,TIP_INGRESO2
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,BAJO,202207,MEDIO
1,7665498,34.0,2500,Soltero,21/07/2022,07665498,BAJO,202207,BAJO

In [61]:
# Utilizando lambda function con una funcion ya definida (Casos complejos)
def genera_tipingreso(ingreso, edad):
  if ingreso > 4000:
    result = 'ALTO'
  elif ingreso > 2000 and edad < 30:
    result = 'MEDIO'
  else:
    result = 'BAJO'
  return result

In [62]:
df_clase['TIP_INGRESO3'] = df_clase[[
    'ingreso', 'edad']].apply(lambda x: genera_tipingreso(x['ingreso'], x['edad']), axis=1)
df_clase.head(2)

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,TIP_INGRESO,CODMESMATRICULA,TIP_INGRESO2,TIP_INGRESO3
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,BAJO,202207,MEDIO,MEDIO
1,7665498,34.0,2500,Soltero,21/07/2022,07665498,BAJO,202207,BAJO,BAJO

# Interactuando con Fechas

In [63]:
from datetime import datetime

In [64]:
df_clase['DATETIME'] = df_clase['fecmatricula'].apply(lambda x: datetime.strptime(x, "%d/%m/%Y"))
df_clase.iloc[:2, [0,1,2,3,4,7,-1]]

    codigo  edad  ingreso estado_civil fecmatricula CODMESMATRICULA   DATETIME
0  9876654  26.0     2500      Soltero   25/07/2022          202207 2022-07-25
1  7665498  34.0     2500      Soltero   21/07/2022          202207 2022-07-21

In [65]:
df_clase['CODMES'] = df_clase[
    'fecmatricula'].apply(lambda x: datetime.strptime(x, "%d/%m/%Y").strftime('%Y%m'))
df_clase.iloc[:2, [0,1,2,3,4,7,-2,-1]]

,codigo,edad,ingreso,estado_civil,fecmatricula,CODMESMATRICULA,DATETIME,CODMES
0,9876654,26.0,2500,Soltero,25/07/2022,202207,2022-07-25,202207
1,7665498,34.0,2500,Soltero,21/07/2022,202207,2022-07-21,202207

In [66]:
df_clase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   codigo           5 non-null      int64
 1   edad             5 non-null      float64
 2   ingreso          5 non-null      int64
 3   estado_civil     5 non-null      object
 4   fecmatricula     5 non-null      object
 5   DNI              5 non-null      object
 6   TIP_INGRESO      5 non-null      object
 7   CODMESMATRICULA  5 non-null      object
 8   TIP_INGRESO2     5 non-null      object
 9   TIP_INGRESO3     5 non-null      object
 10  DATETIME         5 non-null      datetime64[ns]
 11  CODMES           5 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(2), object(8)
memory usage: 612.0+ bytes

# Renombrando Columnas

In [67]:
df_clase.rename(columns = {'TIP_INGRESO2': 'NEW_TIPING', 'TIP_INGRESO3':'TEST_TIPING'}, inplace=True)
df_clase.head()

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,TIP_INGRESO,CODMESMATRICULA,NEW_TIPING,TEST_TIPING,DATETIME,CODMES
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,BAJO,202207,MEDIO,MEDIO,2022-07-25,202207
1,7665498,34.0,2500,Soltero,21/07/2022,07665498,BAJO,202207,BAJO,BAJO,2022-07-21,202207
2,6598764,30.0,3500,Casado,28/07/2022,06598764,ALTO,202207,BAJO,BAJO,2022-07-28,202207
3,5498766,42.0,4800,Casado,26/07/2022,05498766,ALTO,202207,ALTO,ALTO,2022-07-26,202207
4,8976654,38.0,4100,Soltero,22/07/2022,08976654,ALTO,202207,ALTO,ALTO,2022-07-22,202207

# Mapeando campos: .map()

In [68]:
df_clase['DETINGRESO'] = df_clase['TIP_INGRESO'].map({
    'BAJO': 'Ingreso bajo',
    'MEDIO': 'Ingreso medio',
    'ALTO': 'Ingreso alto',
})
df_clase.iloc[[0,2], [0,1,2,3,4,6,-3,-2,-1]]

,codigo,edad,ingreso,estado_civil,fecmatricula,TIP_INGRESO,DATETIME,CODMES,DETINGRESO
0,9876654,26.0,2500,Soltero,25/07/2022,BAJO,2022-07-25,202207,Ingreso bajo
2,6598764,30.0,3500,Casado,28/07/2022,ALTO,2022-07-28,202207,Ingreso alto

# Guardado de un Dataframe

In [71]:
df_clase.to_csv('/content/drive/MyDrive/Datasets/dataframes/df_clase.csv', index=False)

In [72]:
df_clase.to_json('/content/drive/MyDrive/Datasets/dataframes/df_clase.json', orient='records', lines=True)

In [74]:
import os

db_path = '/content/drive/MyDrive/Datasets/dataframes/my_database.db'

if os.path.exists(db_path):
    os.remove(db_path)

In [75]:
from sqlalchemy import create_engine

engine = create_engine('sqlite:////content/drive/MyDrive/Datasets/dataframes/my_database.db')
df_clase.to_sql('df_clase', con=engine, index=False, if_exists='replace')

5

In [76]:
# query = "SELECT * FROM df_clase"
# df_query = pd.read_sql_query(query, engine)
df_table = pd.read_sql_table('df_clase', engine)
df_table.head()

,codigo,edad,ingreso,estado_civil,fecmatricula,DNI,TIP_INGRESO,CODMESMATRICULA,NEW_TIPING,TEST_TIPING,DATETIME,CODMES,DETINGRESO
0,9876654,26.0,2500,Soltero,25/07/2022,09876654,BAJO,202207,MEDIO,MEDIO,2022-07-25,202207,Ingreso bajo
1,7665498,34.0,2500,Soltero,21/07/2022,07665498,BAJO,202207,BAJO,BAJO,2022-07-21,202207,Ingreso bajo
2,6598764,30.0,3500,Casado,28/07/2022,06598764,ALTO,202207,BAJO,BAJO,2022-07-28,202207,Ingreso alto
3,5498766,42.0,4800,Casado,26/07/2022,05498766,ALTO,202207,ALTO,ALTO,2022-07-26,202207,Ingreso alto
4,8976654,38.0,4100,Soltero,22/07/2022,08976654,ALTO,202207,ALTO,ALTO,2022-07-22,202207,Ingreso alto