# **Pandas I**
Expositor: Angel Tintaya

# Summary:


1. Pandas: Series y Dataframes
2. Agrupaciones

# **Pandas ==> Series y Dataframe**


---


- Creación de un dataframe desde una ruta
- Creación de un dataframe desde un link
- Creación de un dataframe: Diccionario de Listas
- Analizar datos con pandas: .head(), .tail(), .describe(), .info(), .isnull(), .any(), .unique(), .nunique()
- Propiedades: shape, columns, index
- Series vs DataFrame
- Filtrando Series
- Seleccionando campos

In [3]:
import pandas as pd
import numpy as np

# Creación y Guardado de un Dataframe

In [4]:
# Creación de un dataframe desde una ruta
df_drive_pkmn = pd.read_csv('/content/drive/MyDrive/Datasets/pokemon.txt')
print(type(df_drive_pkmn))
df_drive_pkmn.head(2)

<class 'pandas.core.frame.DataFrame'>

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False

In [5]:
# Creación de un dataframe desde un link
df_link_pokemon = pd.read_csv('https://raw.githubusercontent.com/AngelTintaya/datasets/main/pokemon.csv')
print(type(df_link_pokemon))
df_link_pokemon.head(2)

<class 'pandas.core.frame.DataFrame'>

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False

In [6]:
# Creación de un dataframe: Diccionario de listas
dic_clase = {'codigo':[9876654,7665498,6598764,5498766,8976654],
             'edad':[26,np.nan,30,42,38],
             'ingreso':[2500,2500,3500,4800,4100],
             'estado_civil':['Soltero','Soltero','Casado','Casado','Soltero'],
             'fecmatricula':['25/07/2022','21/07/2022','28/07/2022','26/07/2022','22/07/2022']
            }
print(type(dic_clase))

<class 'dict'>

In [7]:
df_clase = pd.DataFrame(dic_clase)
df_clase

    codigo  edad  ingreso estado_civil fecmatricula
0  9876654  26.0     2500      Soltero   25/07/2022
1  7665498   NaN     2500      Soltero   21/07/2022
2  6598764  30.0     3500       Casado   28/07/2022
3  5498766  42.0     4800       Casado   26/07/2022
4  8976654  38.0     4100      Soltero   22/07/2022

In [8]:
# Guardado de un DataFrame
df_clase.to_csv('/content/drive/MyDrive/Datasets/new_df.tsv', sep='\t', index=False)

In [9]:
df_clase.head(2)

    codigo  edad  ingreso estado_civil fecmatricula
0  9876654  26.0     2500      Soltero   25/07/2022
1  7665498   NaN     2500      Soltero   21/07/2022

In [10]:
# Ejemplo Serie
print(f"Type: {type(df_drive_pkmn['Name'][:3])}\n")
df_drive_pkmn['Name'][:3]

Type: <class 'pandas.core.series.Series'>

0    Bulbasaur
1      Ivysaur
2     Venusaur
Name: Name, dtype: object

In [11]:
# Ejemplo Dataframe
print(f"Type: {type(df_drive_pkmn[['Name', 'Type 1']][:3])}\n")
df_drive_pkmn[['Name', 'Type 1']][:3]

Type: <class 'pandas.core.frame.DataFrame'>

        Name Type 1
0  Bulbasaur  Grass
1    Ivysaur  Grass
2   Venusaur  Grass

In [12]:
# Valores faltantes
np.nan

nan

# Analizar datos con pandas
- .head()
- .tail()
- .describe()
- .info()
- .isnull()
- .any()
- .unique()
- .nunique()

In [13]:
df_clase

    codigo  edad  ingreso estado_civil fecmatricula
0  9876654  26.0     2500      Soltero   25/07/2022
1  7665498   NaN     2500      Soltero   21/07/2022
2  6598764  30.0     3500       Casado   28/07/2022
3  5498766  42.0     4800       Casado   26/07/2022
4  8976654  38.0     4100      Soltero   22/07/2022

In [14]:
# Método head: Obtiene los primeros registros de un Dataframe
df_clase.head(2)

    codigo  edad  ingreso estado_civil fecmatricula
0  9876654  26.0     2500      Soltero   25/07/2022
1  7665498   NaN     2500      Soltero   21/07/2022

In [15]:
# Método tail: Obtiene los últimos registros de un Dataframe
df_clase.tail(3)

    codigo  edad  ingreso estado_civil fecmatricula
2  6598764  30.0     3500       Casado   28/07/2022
3  5498766  42.0     4800       Casado   26/07/2022
4  8976654  38.0     4100      Soltero   22/07/2022

In [16]:
# Método describe: Genera un resumen estadístico de los datos numéricos
df_clase.describe()

             codigo       edad      ingreso
count  5.000000e+00   4.000000     5.000000
mean   7.723267e+06  34.000000  3480.000000
std    1.762406e+06   7.302967  1005.982107
min    5.498766e+06  26.000000  2500.000000
25%    6.598764e+06  29.000000  2500.000000
50%    7.665498e+06  34.000000  3500.000000
75%    8.976654e+06  39.000000  4100.000000
max    9.876654e+06  42.000000  4800.000000

In [17]:
# Método info: Obteniendo informacion de cada campo del dataframe
df_clase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   codigo        5 non-null      int64
 1   edad          4 non-null      float64
 2   ingreso       5 non-null      int64
 3   estado_civil  5 non-null      object
 4   fecmatricula  5 non-null      object
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [18]:
# Método isnull: Un alias de 'isna', detecta valores faltantes, retorna booleanos
df_clase.isnull()

   codigo   edad  ingreso  estado_civil  fecmatricula
0   False  False    False         False         False
1   False   True    False         False         False
2   False  False    False         False         False
3   False  False    False         False         False
4   False  False    False         False         False

In [19]:
# Método isna: Detecta valores faltantes, retorna booleanos
df_clase.isna()

   codigo   edad  ingreso  estado_civil  fecmatricula
0   False  False    False         False         False
1   False   True    False         False         False
2   False  False    False         False         False
3   False  False    False         False         False
4   False  False    False         False         False

In [20]:
# Mêtodo any: Devuelve verdadero si algun elemento es verdadero
# # Seguido de isnull, devuelve que columnas tienen algun valor verdadero
df_clase.isnull().any()

codigo          False
edad             True
ingreso         False
estado_civil    False
fecmatricula    False
dtype: bool

In [21]:
# # Seguido de isnull().any() indica si el dataframe tiene algun valor verdadero
df_clase.isnull().any().any()

np.True_

In [22]:
# Método unique: Retorna valores únicos
df_clase['ingreso'].unique()

array([2500, 3500, 4800, 4100])

In [23]:
# Cuenta el número de elementos distintos
df_clase.nunique()

codigo          5
edad            4
ingreso         4
estado_civil    2
fecmatricula    5
dtype: int64

In [24]:
# Método notnull (or notna): Retorna verdadero si se posee un valor
df_clase.notnull()

   codigo   edad  ingreso  estado_civil  fecmatricula
0    True   True     True          True          True
1    True  False     True          True          True
2    True   True     True          True          True
3    True   True     True          True          True
4    True   True     True          True          True

In [25]:
# Mêtodo all: Devuelve verdadero si todos los elementos son verdaderos
df_clase.notnull().all()

codigo           True
edad            False
ingreso          True
estado_civil     True
fecmatricula     True
dtype: bool

# Propiedades de un Dataframe
- .shape
- .columns
- .index

In [26]:
# Shape: Nos indica el número de filas y columnas (en formato tupla) de un Dataframe
df_clase.shape

(5, 5)

In [27]:
# Columns: Nos muestra los valores de las columnas de un dataframe
df_clase.columns

Index(['codigo', 'edad', 'ingreso', 'estado_civil', 'fecmatricula'], dtype='object')

In [28]:
# Nos muestra la secuencia de los índices del dataframe
df_clase.index

RangeIndex(start=0, stop=5, step=1)

# Trabajando con Series

In [29]:
# Identificando una serie a partir de un dataframe
type(df_clase['ingreso'])

pandas.core.series.Series

In [30]:
df_clase['ingreso']

0    2500
1    2500
2    3500
3    4800
4    4100
Name: ingreso, dtype: int64

In [31]:
# Slicing: Extrayendo partes de una serie
df_clase['ingreso'][1:3]

1    2500
2    3500
Name: ingreso, dtype: int64

In [32]:
df_clase['ingreso'][3:]

3    4800
4    4100
Name: ingreso, dtype: int64

In [33]:
df_clase.ingreso[:2]

0    2500
1    2500
Name: ingreso, dtype: int64

# Seleccionando Campos

In [34]:
type(df_clase[['ingreso']])

pandas.core.frame.DataFrame

In [35]:
df_clase[['ingreso']]

   ingreso
0     2500
1     2500
2     3500
3     4800
4     4100

In [36]:
df_clase[['ingreso','codigo','edad']]

   ingreso   codigo  edad
0     2500  9876654  26.0
1     2500  7665498   NaN
2     3500  6598764  30.0
3     4800  5498766  42.0
4     4100  8976654  38.0

In [37]:
df_clase[['codigo', 'ingreso', 'edad']][:3]

    codigo  ingreso  edad
0  9876654     2500  26.0
1  7665498     2500   NaN
2  6598764     3500  30.0

# **Pandas ==> Agrupaciones**

---


- Método groupby
- Agrupaciones Directas
- Agrupaciones por agregación
- Agrupaciones independientes al campo
- Agrupacion múltiple
- Bono: Renombrado de columnas
- Bono: Reseteo de índices

# Agrupaciones Directas

In [38]:
df_base = df_drive_pkmn[:16]
df_base

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False

In [39]:
df_base.head(1)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False

In [40]:
# Método groupby: Permite agrupar grandes cantidades de datos y calcular operaciones en estos grupos
gb_base = df_base.groupby('Type 1')
type(gb_base)

pandas.core.groupby.generic.DataFrameGroupBy

In [41]:
# Cantidad de registros agrupados
# # Agrupa y muestra la cantidad de registros con un valor
gb_base = df_base.groupby('Type 1')
gb_base.count()

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,,
Bug,3,3,1,3,3,3,3,3,3,3,3,3
Fire,5,5,3,5,5,5,5,5,5,5,5,5
Grass,4,4,4,4,4,4,4,4,4,4,4,4
Water,4,4,0,4,4,4,4,4,4,4,4,4

In [42]:
gb_base = df_base.groupby('Type 2', dropna=False)
gb_base.count()

,#,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 2,,,,,,,,,,,,
Dragon,1,1,1,1,1,1,1,1,1,1,1,1
Flying,3,3,3,3,3,3,3,3,3,3,3,3
Poison,4,4,4,4,4,4,4,4,4,4,4,4
NaN,8,8,8,8,8,8,8,8,8,8,8,8

In [43]:
# # Agrupación mostrando una Serie
gb_base = df_base.groupby('Type 1')['#']
gb_base.count()

Type 1
Bug      3
Fire     5
Grass    4
Water    4
Name: #, dtype: int64

In [44]:
# # Agrupación mostrando un Dataframe
gb_base = df_base.groupby('Type 1')[['#', 'Type 2']]
gb_base.count()

        #  Type 2
Type 1
Bug     3       1
Fire    5       3
Grass   4       4
Water   4       0

In [45]:
# Máximo valor de una agrupación
gb_base = df_base.groupby('Type 1')[['Attack', 'Sp. Atk']]
gb_base.max()

        Attack  Sp. Atk
Type 1
Bug         45       90
Fire       130      159
Grass      100      122
Water      103      135

In [46]:
# Mínimo valor de una agrupación
gb_base = df_base.groupby('Type 1')[['Attack', 'Sp. Atk']]
gb_base.min()

        Attack  Sp. Atk
Type 1
Bug         20       20
Fire        52       60
Grass       49       65
Water       48       50

In [47]:
# Mediana de una agrupación
gb_base = df_base.groupby('Type 1')[['Attack', 'Sp. Atk']]
gb_base.median()

        Attack  Sp. Atk
Type 1
Bug       30.0     25.0
Fire      84.0    109.0
Grass     72.0     90.0
Water     73.0     75.0

In [48]:
# Promedio de una agrupación
gb_base = df_base.groupby('Type 1')[['Attack', 'Sp. Atk']]
gb_base.mean()

           Attack  Sp. Atk
Type 1
Bug     31.666667    45.00
Fire    86.800000   107.60
Grass   73.250000    91.75
Water   74.250000    83.75

# Agrupaciones por agregación

In [49]:
# Total de registros, mínimo y máximo valor por determinada columna
gb_base = df_base.groupby('Type 1')[['Attack']]
gb_base.agg(['count','min','max'])

       Attack
        count min  max
Type 1
Bug         3  20   45
Fire        5  52  130
Grass       4  49  100
Water       4  48  103

# Agrupaciones con múltiples campos

In [50]:
# Total de registros, mínimo y máximo valor por determinada columna
gb_base = df_base.groupby('Type 1')[['Attack', 'Sp. Atk']]
gb_base.agg(['count','min','max'])

       Attack          Sp. Atk
        count min  max   count min  max
Type 1
Bug         3  20   45       3  20   90
Fire        5  52  130       5  60  159
Grass       4  49  100       4  65  122
Water       4  48  103       4  50  135

# Agrupaciones independientes al campo

In [51]:
# Filtro de tipo de agrupación por campo
gb_base = df_base.groupby('Type 1')[['#', 'Attack', 'Sp. Atk']]
gb_base.agg({'#':'count','Attack':['min','max'],'Sp. Atk':'max'})

           # Attack      Sp. Atk
       count    min  max     max
Type 1
Bug        3     20   45      90
Fire       5     52  130     159
Grass      4     49  100     122
Water      4     48  103     135

# Agrupacion múltiple

In [52]:
gb_base = df_base.groupby(['Type 1','Type 2'], dropna=False)[['Attack', 'Sp. Atk']]
gb_base = gb_base.agg({'Attack':'max','Sp. Atk':['min','max']})
gb_base

              Attack Sp. Atk
                 max     min  max
Type 1 Type 2
Bug    Flying     45      90   90
       NaN        30      20   25
Fire   Dragon    130     130  130
       Flying    104     109  159
       NaN        64      60   80
Grass  Poison    100      65  122
Water  NaN       103      50  135

In [53]:
print(type(gb_base))

<class 'pandas.core.frame.DataFrame'>

In [54]:
print('Total COLUMNAS:',len(gb_base.columns))
print('COLUMNAS:',gb_base.columns)

Total COLUMNAS: 3
COLUMNAS: MultiIndex([( 'Attack', 'max'),
            ('Sp. Atk', 'min'),
            ('Sp. Atk', 'max')],
           )

In [55]:
print('Total INDICES:',len(gb_base.index))
print('INDICES:',gb_base.index)

Total INDICES: 7
INDICES: MultiIndex([(  'Bug', 'Flying'),
            (  'Bug',      nan),
            ( 'Fire', 'Dragon'),
            ( 'Fire', 'Flying'),
            ( 'Fire',      nan),
            ('Grass', 'Poison'),
            ('Water',      nan)],
           names=['Type 1', 'Type 2'])

# Bono: Renombrado de columnas

In [56]:
# Renombrado de todas las columnas de un Dataframe
gb_base.columns = ['max_attack', 'min_sp_attack', 'max_sp_attack']
gb_base

               max_attack  min_sp_attack  max_sp_attack
Type 1 Type 2
Bug    Flying          45             90             90
       NaN             30             20             25
Fire   Dragon         130            130            130
       Flying         104            109            159
       NaN             64             60             80
Grass  Poison         100             65            122
Water  NaN            103             50            135

In [57]:
# Renombrado de determinadas columnas en un DataFrame
gb_base.rename(columns={'min_sp_attack': 'min_spatk', 'max_sp_attack': 'max_spatk'}, inplace=True)
gb_base

               max_attack  min_spatk  max_spatk
Type 1 Type 2
Bug    Flying          45         90         90
       NaN             30         20         25
Fire   Dragon         130        130        130
       Flying         104        109        159
       NaN             64         60         80
Grass  Poison         100         65        122
Water  NaN            103         50        135

# Bono: Reseteo de índices

In [58]:
# Reseteando índices en un Dataframe
gb_base.reset_index(inplace=True)
gb_base

  Type 1  Type 2  max_attack  min_spatk  max_spatk
0    Bug  Flying          45         90         90
1    Bug     NaN          30         20         25
2   Fire  Dragon         130        130        130
3   Fire  Flying         104        109        159
4   Fire     NaN          64         60         80
5  Grass  Poison         100         65        122
6  Water     NaN         103         50        135

In [59]:
# Reseteo de índice sin guardar el índice actual
gb_base.reset_index(drop=True)

  Type 1  Type 2  max_attack  min_spatk  max_spatk
0    Bug  Flying          45         90         90
1    Bug     NaN          30         20         25
2   Fire  Dragon         130        130        130
3   Fire  Flying         104        109        159
4   Fire     NaN          64         60         80
5  Grass  Poison         100         65        122
6  Water     NaN         103         50        135

In [60]:
df_base.head(1)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False

### Lectura de XML en Pandas

In [61]:
xml_text = '''<?xml version="1.0"?>
<Catalog>
   <Book id="bk101">
      <Author>Garghentini, Davide</Author>
      <Title>XML Developer's Guide</Title>
      <Genre>Computer</Genre>
      <Price>44.95</Price>
      <PublishDate>2000-10-01</PublishDate>
      <Description>An in-depth look at creating applications
      with XML.</Description>
   </Book>
   <Book id="bk102">
      <Author>Garcia, Debra</Author>
      <Title>Midnight Rain</Title>
      <Genre>Fantasy</Genre>
      <Price>5.95</Price>
      <PublishDate>2000-12-16</PublishDate>
      <Description>A former architect battles corporate zombies,
      an evil sorceress, and her own childhood to become queen
      of the world.</Description>
   </Book>
</Catalog>
'''

In [62]:
pd.read_xml(xml_text)

/tmp/ipython-input-1336251121.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml_text)

,id,Author,Title,Genre,Price,PublishDate,Description
0,bk101,"Garghentini, Davide",XML Developer's Guide,Computer,44.95,2000-10-01,An in-depth look at creating applications\n ...
1,bk102,"Garcia, Debra",Midnight Rain,Fantasy,5.95,2000-12-16,"A former architect battles corporate zombies,\..."

In [63]:
import io
io_xml = io.StringIO(xml_text)

In [64]:
pd.read_xml(io_xml)

,id,Author,Title,Genre,Price,PublishDate,Description
0,bk101,"Garghentini, Davide",XML Developer's Guide,Computer,44.95,2000-10-01,An in-depth look at creating applications\n ...
1,bk102,"Garcia, Debra",Midnight Rain,Fantasy,5.95,2000-12-16,"A former architect battles corporate zombies,\..."